name: Build and Deploy to Minikube

on:
  push:
    branches:
      - main  # Change this to your default branch if it's different

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
    - name: Check out code
      uses: actions/checkout@v4
        
    - name: Login to Container Registry
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        
    - name: Build Docker image
      run: sudo docker build -t skroyal23/wisecow-app:v1 .
      
    - name: Push Docker image
      run: sudo docker push skroyal23/wisecow-app:v1
          
    - name: Deploy to Kubernetes
      run: |
          sudo kubectl apply -f wisecow.yaml
          sudo kubectl wait --for=condition=ready pod -l app=wisecow
          sudo minikube service list
          sudo minikube service wisecow-service --url
          echo "------------------opening the service------------------"
          curl $(sudo minikube service wisecow-service --url)

          
   
