name: Docker Build, Push, and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-push-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image
        run:  |
          docker build -t skroyal23/wisecow-app:latest .
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker push skroyal23/wisecow-app:latest
      
      - name: Deploy to Kubernates
        run:  |
          kubectl apply -f deployment_manifests_kubernetes.yaml --validate=false
          kubectl apply -f service_manifests_kubernetes
