apiVersion: v1
kind: Config
clusters:
- name: wisecow-service
  cluster:
    server: https://10.96.62.117:4499
    certificate-authority-data: <base64-encoded-ca-certificate>
contexts:
- name: ClusterContext
  context:
    cluster: wisecow-service
    user: saikrishna26
current-context: my-context
users:
- name: saikrishna
  user:
    <authentication-method-configuration>
